// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SwimBikeRun.Data;

#nullable disable

namespace SwimBikeRun.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260615164046_DurchschnittsPaceHinzugefuegt")]
    partial class DurchschnittsPaceHinzugefuegt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("SwimBikeRun.Models.Trainingseinheit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<int>("DauerMinuten")
                        .HasColumnType("INTEGER");

                    b.Property<double>("DistanzKm")
                        .HasColumnType("REAL");

                    b.Property<double?>("DurchschnittsPace")
                        .HasColumnType("REAL");

                    b.Property<string>("Notiz")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sportart")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Trainingseinheiten");
                });
#pragma warning restore 612, 618
        }
    }
}
